name: ssr
channels:
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=10.2  # 11.6
#  - mkl=2022.1  # for Intel
  - nomkl=3.0  # for AMD
  - pip=21.3
  - python=3.7  # 3.9
  - pip:
    - datasets==2.4.0
    - evaluate==0.2.2
    # - fairseq==0.10.2  # 0.12.2
    - faiss-gpu==1.7.2
    - fastBPE==0.1.0
    - gdown==4.5.1
    - numpy==1.21.6  # for Pyhton 3.7
    - rouge-score==0.1.2  # dependent by load_metric
    - sacrebleu==1.5.1  # 2.1.0
    - sacremoses==0.0.53
    - sentencepiece==0.1.96
    - torch==1.11.0  # 1.12.0
    - tqdm==4.64.0
    - transformers==4.21.0
#    - torch-scatter==2.0.9 -f https://data.pyg.org/whl/torch-1.11.0+cu102.html
#    - git+https://github.com/Maluuba/nlg-eval.git@master

# nlg-eval --setup
# pip3 install --editable ./
# rm -r $(find . -name '*.egg-info')
# MANUALLY INSTALL fairseq torch-scatter nlg-eval rouge_score

# [ADD]
# conda env create -f conda.yml
# [CHECK]
# conda env list
# [REMOVE]
# conda env remove --name ssr
# [UPDATE]
# conda env update --name ssr --file conda.yml --prune
